"""Add guest and role fields

Revision ID: 3f41fee53b08
Revises: 7cb74f9b3319
Create Date: 2026-07-28 05:27:49.941048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f41fee53b08'
down_revision: Union[str, Sequence[str], None] = '7cb74f9b3319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_target_audiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('conversation_type', sa.Enum('direct', 'group', 'project', name='conversationtype'), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'completed', name='conversationstatus'), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copilot_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('dashboard_context', sa.String(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=True),
    sa.Column('copilot_mode', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practical_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('agenda_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('task_packages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_fallback_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('milestone_timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personal_todos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stakeholder_todos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toolboxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('project_summary', sa.Text(), nullable=True),
    sa.Column('preparation_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('followup_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('method_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('communication_tips', sa.Text(), nullable=True),
    sa.Column('risk_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_attachment_path', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_contributors',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.drop_table('bot_logs')
    op.drop_table('guest_sessions')
    op.drop_table('ai_interpretations')
    op.add_column('block_answers', sa.Column('flow_progress_id', sa.UUID(), nullable=True))
    op.add_column('block_answers', sa.Column('block_number', sa.Integer(), nullable=False))
    op.add_column('block_answers', sa.Column('needs_review', sa.Boolean(), nullable=True))
    op.add_column('block_answers', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'block_answers', 'core_flow_progress', ['flow_progress_id'], ['id'])
    op.drop_column('block_answers', 'is_detailed_mode')
    op.drop_column('block_answers', 'block_id')
    op.add_column('core_flow_progress', sa.Column('block_1_completed', sa.Boolean(), nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_2_completed', sa.Boolean(), nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_3_completed', sa.Boolean(), nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_4_completed', sa.Boolean(), nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_5_completed', sa.Boolean(), nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_6_completed', sa.Boolean(), nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_7_completed', sa.Boolean(), nullable=True))
    op.alter_column('core_flow_progress', 'current_block',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='current_block::integer',
               existing_nullable=True)
    op.drop_column('core_flow_progress', 'block_b_completed')
    op.drop_column('core_flow_progress', 'block_f_completed')
    op.drop_column('core_flow_progress', 'block_c_completed')
    op.drop_column('core_flow_progress', 'block_e_completed')
    op.drop_column('core_flow_progress', 'block_a_completed')
    op.drop_column('core_flow_progress', 'block_g_completed')
    op.drop_column('core_flow_progress', 'block_d_completed')
    op.add_column('document_uploads', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('document_uploads', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('document_uploads', sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('document_uploads', sa.Column('extraction_status', sa.String(), nullable=True))
    op.add_column('document_uploads', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('document_uploads', 'ai_analysis_result')
    # org_role is already String
    op.add_column('projects', sa.Column('guest_session_id', sa.String(), nullable=True))
    project_status_enum = postgresql.ENUM('idea_draft', 'active_execution', 'paused', 'completed', 'archived', name='projectstatus')
    project_status_enum.create(op.get_bind())
    op.add_column('projects', sa.Column('status', sa.Enum('idea_draft', 'active_execution', 'paused', 'completed', 'archived', name='projectstatus'), nullable=True))
    
    planning_mode_enum = postgresql.ENUM('express', 'detailed', name='planningmode')
    planning_mode_enum.create(op.get_bind())
    op.add_column('projects', sa.Column('planning_mode', sa.Enum('express', 'detailed', name='planningmode'), nullable=True))
    op.add_column('projects', sa.Column('sustainability_notes', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('inclusivity_notes', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('transparency_notes', sa.String(), nullable=True))
    op.drop_column('projects', 'current_mode')
    op.drop_column('projects', 'lifecycle_status')
    op.drop_column('projects', 'is_template')
    op.drop_column('projects', 'initial_mode')
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('users', sa.Column('is_guest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('privacy_consent', sa.Boolean(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['session_id'])
    op.drop_column('users', 'opt_in_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('opt_in_data', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'privacy_consent')
    op.drop_column('users', 'session_id')
    op.drop_column('users', 'is_guest')
    op.alter_column('tasks', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('projects', sa.Column('initial_mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('lifecycle_status', postgresql.ENUM('idea_draft', 'active_execution', 'paused', 'archived_research', name='projectlifecyclestatus'), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('current_mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'transparency_notes')
    op.drop_column('projects', 'inclusivity_notes')
    op.drop_column('projects', 'sustainability_notes')
    op.drop_column('projects', 'planning_mode')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'guest_session_id')
    # org_role is String
    op.add_column('document_uploads', sa.Column('ai_analysis_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('document_uploads', 'extracted_at')
    op.drop_column('document_uploads', 'extraction_status')
    op.drop_column('document_uploads', 'extracted_data')
    op.drop_column('document_uploads', 'file_size_bytes')
    op.drop_column('document_uploads', 'file_type')
    op.add_column('core_flow_progress', sa.Column('block_d_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_g_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_a_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_e_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_c_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_f_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('core_flow_progress', sa.Column('block_b_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('core_flow_progress', 'current_block',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('core_flow_progress', 'block_7_completed')
    op.drop_column('core_flow_progress', 'block_6_completed')
    op.drop_column('core_flow_progress', 'block_5_completed')
    op.drop_column('core_flow_progress', 'block_4_completed')
    op.drop_column('core_flow_progress', 'block_3_completed')
    op.drop_column('core_flow_progress', 'block_2_completed')
    op.drop_column('core_flow_progress', 'block_1_completed')
    op.add_column('block_answers', sa.Column('block_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('block_answers', sa.Column('is_detailed_mode', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'block_answers', type_='foreignkey')
    op.drop_column('block_answers', 'confirmed_at')
    op.drop_column('block_answers', 'needs_review')
    op.drop_column('block_answers', 'block_number')
    op.drop_column('block_answers', 'flow_progress_id')
    op.create_table('ai_interpretations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ai_interpretation_summary', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('generated_by_agent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('ai_interpretations_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_interpretations_pkey'))
    )
    op.create_table('guest_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_guest', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dsgvo_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('converted_to_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['converted_to_user_id'], ['users.id'], name=op.f('guest_sessions_converted_to_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('guest_sessions_pkey'))
    )
    op.create_table('bot_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_identified_gap', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_suggestion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('bot_logs_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_logs_pkey'))
    )
    op.drop_table('task_contributors')
    op.drop_table('messages')
    op.drop_table('conversation_participants')
    op.drop_table('toolboxes')
    op.drop_table('project_snapshots')
    op.drop_table('practical_plans')
    op.drop_table('milestones')
    op.drop_table('copilot_messages')
    op.drop_table('conversations')
    op.drop_table('saved_target_audiences')
    op.drop_table('project_templates')
    op.drop_table('notifications')
    # ### end Alembic commands ###
