"""Add TeamMember and Budget to Project

Revision ID: 43b3832d5b01
Revises: 3117556aac2e
Create Date: 2026-07-31 09:51:33.142654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b3832d5b01'
down_revision: Union[str, Sequence[str], None] = '3117556aac2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_role', sa.Enum('owner', 'editor', 'viewer', name='teamrole'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('budget_used', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('budget_total', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'budget_total')
    op.drop_column('projects', 'budget_used')
    op.drop_table('team_members')
    # ### end Alembic commands ###
